# CogniPlan Planner Node Configuration

# Model parameters
model_path: "checkpoints/cogniplan_exp_pred7"
generator_path: "checkpoints/wgan_inpainting"
use_gpu: false
model_input_size: [224, 224]  # [height, width]

# Velocity limits
max_linear_vel: 0.5   # m/s
max_angular_vel: 1.0  # rad/s
min_linear_vel: 0.0   # m/s
min_angular_vel: 0.0  # rad/s

# Safety parameters
min_obstacle_distance: 0.5  # m
safety_margin: 0.2      # m

# Planning parameters
planning_horizon: 10    # steps
planning_frequency: 10  # Hz
goal_tolerance: 0.3     # m

# Sensor parameters
laser_scan_topic: "/scan"
odom_topic: "/odom"
cmd_vel_topic: "/cmd_vel"

# Frame parameters
map_frame: "map"
odom_frame: "odom"
base_frame: "base_link"

# Debug parameters
debug_mode: false
log_level: "INFO"